/* eslint-disable */
"use client";
import React from "react";
import { motion } from "motion/react";
import { MarketingNav } from "../../components/marketing-nav";

export default function SkillPage() {
  return (
    <div className="bg-background text-on-background font-sans min-h-[100dvh] flex flex-col flex-1 w-full relative">
      
      {/* ETHEREAL GLASS BACKGROUND MESH */}
      <div className="fixed inset-0 z-0 pointer-events-none opacity-20 opacity-40">
        <div className="absolute top-[-20%] left-[-10%] w-[50%] h-[50%] rounded-full bg-[#38bdf8]/10 blur-[120px]" />
        <div className="absolute bottom-[-20%] right-[-10%] w-[50%] h-[50%] rounded-full bg-blue-600/10 blur-[120px]" />
      </div>
      
      {/* NOISE OVERLAY */}
      <div className="fixed inset-0 z-50 pointer-events-none opacity-[0.02]" style={{ backgroundImage: 'url("https://grainy-gradients.vercel.app/noise.svg")' }} />

      {/* MARKETING NAV */}
      <MarketingNav />

      <main className="relative z-10 w-full pt-48 pb-32 max-w-5xl mx-auto px-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1 }}
          className="flex flex-col items-center text-center"
        >
          <h4 className="font-mono text-[13px] uppercase tracking-widest text-[#38bdf8] mb-6">
            AI Agent Integration
          </h4>
          <h1 className="font-serif text-5xl md:text-7xl font-bold tracking-tight text-primary mb-8">
            RESEARCH SKILL<br/><span className="text-on-surface-variant font-light italic">by ScholarSync</span>
          </h1>
          <p className="text-xl text-on-surface-variant font-light mb-12 max-w-2xl">
            A deterministic extraction skill for Antigravity, Claude, and Codex that enforces zero-stochastic drift, absolute cryptographic citation adherence, and Pure Black visual aesthetics.
          </p>
        </motion.div>

        <div className="mt-12 bg-surface-container-low border border-white/5 rounded-3xl p-8 md:p-12 shadow-2xl relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-[#38bdf8] to-transparent opacity-50" />
          
          <h3 className="text-2xl font-serif text-white mb-6">Installation</h3>
          <p className="text-on-surface-variant font-light mb-6">
            Copy the <code className="text-[#38bdf8]">SKILL.md</code> directly into your `.agents/skills/research-skill-scholorsync/` directory to empower your AI coding assistants with deterministic academic retrieval rules.
          </p>
          
          <div className="bg-[#050505] border border-white/5 p-6 rounded-2xl font-mono text-[13px] text-on-surface-variant overflow-x-auto">
<pre><code><span className="text-slate-500"># Create the skill directory</span>
<span className="text-[#38bdf8]">mkdir -p .agents/skills/research-skill-scholorsync</span>

<span className="text-slate-500"># Download the strict instruction set</span>
<span className="text-[#38bdf8]">curl -o .agents/skills/research-skill-scholorsync/SKILL.md https://localresearcher.dev/SKILL.md</span>
</code></pre>
          </div>

          <hr className="border-white/10 my-12" />

          <h3 className="text-2xl font-serif text-white mb-6">Core Directives</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <h4 className="font-mono text-[11px] uppercase tracking-widest text-white mb-3">01. Absolute Determinism</h4>
              <p className="text-[15px] text-on-surface-variant font-light leading-relaxed">
                The AI agent is forbidden from improvising data. If a specific metric, sample size, or claim is not explicitly found in the PDF AST chunk, the agent must output "NOT_SPECIFIED".
              </p>
            </div>
            <div>
              <h4 className="font-mono text-[11px] uppercase tracking-widest text-white mb-3">02. Context Constraints</h4>
              <p className="text-[15px] text-on-surface-variant font-light leading-relaxed">
                The skill overrides default summarization behavior by forcing the agent to evaluate the text solely within the injected tensor arrays. Semantic drift is treated as a critical failure.
              </p>
            </div>
            <div>
              <h4 className="font-mono text-[11px] uppercase tracking-widest text-white mb-3">03. Double-Bezel Visuals</h4>
              <p className="text-[15px] text-on-surface-variant font-light leading-relaxed">
                All UI code generated by the agent must adhere to the pure black (`#000000`) and sky blue (`#38bdf8`) palette, removing light mode toggles and enforcing severe borders.
              </p>
            </div>
            <div>
              <h4 className="font-mono text-[11px] uppercase tracking-widest text-white mb-3">04. Citation Adherence</h4>
              <p className="text-[15px] text-on-surface-variant font-light leading-relaxed">
                Every generated claim must be post-fixed with a strict page reference. The AI is trained to map generated sentences back to the source bounding box index.
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
